# Generated by Django 4.1.1 on 2024-09-13 12:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scoutify2', '0002_rename_comment_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
    ]
