# Generated by Django 4.1.1 on 2024-09-25 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoutify2', '0004_alter_likepost_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followerscount',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers_count', to='scoutify2.profile'),
        ),
    ]
