# Generated by Django 4.1.1 on 2024-10-28 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoutify2', '0005_alter_followerscount_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='livevideo',
            name='channel_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='livevideo',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoutify2.profile'),
        ),
        migrations.AddField(
            model_name='livevideo',
            name='uid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
