# Generated by Django 4.1.1 on 2024-11-04 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scoutify2', '0006_livevideo_channel_name_livevideo_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='messaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_body', models.TextField()),
                ('sent_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoutify2.profile')),
            ],
            options={
                'db_table': 'messaging',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Waiting', 'Waiting')], default='Waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('messages', models.ManyToManyField(blank=True, to='scoutify2.messaging')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoutify2.profile')),
            ],
            options={
                'db_table': 'room',
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Attendee',
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
