# Generated by Django 4.1.1 on 2024-11-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutify2', '0007_messaging_room_remove_meeting_attendees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Closed', 'Closed'), ('Active', 'Active')], default='Waiting', max_length=20),
        ),
    ]
