# Generated by Django 4.1.1 on 2024-12-03 10:50

from django.db import migrations, models
import scoutify2.fileUploadChecker


class Migration(migrations.Migration):

    dependencies = [
        ('scoutify2', '0008_post_uuid_alter_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=scoutify2.fileUploadChecker.ContentTypeRestrictedFileField(upload_to='player_videos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Closed', 'Closed'), ('Active', 'Active'), ('Waiting', 'Waiting')], default='Waiting', max_length=20),
        ),
    ]
