# Generated by Django 4.1.1 on 2025-01-06 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoutify2', '0009_alter_post_video_alter_room_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Visa', 'Visa'), ('MobileMoney', 'MobileMoney')], default='MobileMoney', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoutify2.profile')),
            ],
            options={
                'db_table': 'scoutifii_ad',
                'ordering': ('-created_at',),
            },
        ),
    ]
