# Generated by Django 4.1.1 on 2025-01-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutify2', '0010_ads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='status',
        ),
        migrations.AddField(
            model_name='ads',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ads',
            name='daily_budget',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('All', 'All')], default='All', max_length=20),
        ),
        migrations.AddField(
            model_name='ads',
            name='location',
            field=models.CharField(choices=[('Regional', 'Regional'), ('Local', 'Local')], default='Local', max_length=20),
        ),
        migrations.AddField(
            model_name='ads',
            name='payment',
            field=models.CharField(choices=[('MobileMoney', 'MobileMoney'), ('Visa', 'Visa')], default='MobileMoney', max_length=20),
        ),
        migrations.AddField(
            model_name='ads',
            name='tax',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
    ]
