# Generated by Django 4.1.1 on 2025-01-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutify2', '0011_remove_ads_status_ads_age_ads_daily_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='total_payment',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('All', 'All'), ('Male', 'Male')], default='All', max_length=20),
        ),
        migrations.AlterField(
            model_name='ads',
            name='payment',
            field=models.CharField(choices=[('Visa', 'Visa'), ('MobileMoney', 'MobileMoney')], default='MobileMoney', max_length=20),
        ),
    ]
