# Generated by Django 4.1.1 on 2025-01-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutify2', '0012_ads_total_payment_alter_ads_gender_alter_ads_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='payment',
        ),
        migrations.AddField(
            model_name='ads',
            name='payment_method',
            field=models.CharField(choices=[('MobileMoney', 'MobileMoney'), ('Visa', 'Visa')], default='MobileMoney', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Closed', 'Closed'), ('Waiting', 'Waiting'), ('Active', 'Active')], default='Waiting', max_length=20),
        ),
    ]
