# Generated by Django 4.1.1 on 2025-03-19 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoutify2', '0013_remove_ads_payment_ads_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('All', 'All')], default='All', max_length=20),
        ),
        migrations.AlterField(
            model_name='ads',
            name='payment_method',
            field=models.CharField(choices=[('Visa', 'Visa'), ('MobileMoney', 'MobileMoney')], default='MobileMoney', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Closed', 'Closed'), ('Active', 'Active')], default='Waiting', max_length=20),
        ),
        migrations.CreateModel(
            name='FaceRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('face_encoding', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoutify2.profile')),
            ],
            options={
                'db_table': 'face_recognition',
                'ordering': ('-created_at',),
            },
        ),
    ]
